os: Visual Studio 2015

platform: x64

configuration:
  - Debug
  - Release

init:
    - cmd: cmake --version
    - cmd: msbuild /version

before_build:
  - cmd: if not exist "build" mkdir build
  - cmd: cd build
  - cmd: cmake.exe .. -G "Visual Studio 14 2015 Win64"

build:
  project: build/Engine.sln
