os: Visual Studio 2015

platform: x64

configuration:
  - Debug
  - Release

build:
  project: build/Engine.sln

before_build:
  - if not exist "build" mkdir build
  - cd build
  - "C:\\Program Files (x86)\\cmake\\bin\\cmake.exe" .. -G "Visual Studio 14 2015 Win64"
