os: Visual Studio 2015

environment:
  matrix:
  - TOOLSET: vs2015

platform: x64

configuration:
  - Debug
  - Release

build:
  project: build/Engine.sln


before_build:
  - echo Running cmake...
  - cd build
  - cmake .. -G "Visual Studio 14 2015 Win64"
